ALTER TABLE FECHASINGRESO DROP CONSTRAINT INTEG_57;
commit;
ALTER TABLE FECHASINGRESO ALTER IDFECHAINGRESO TYPE Integer;
commit;
alter table FECHASINGRESO
add constraint PK_FECHASINGRESO_1
primary key (IDFECHAINGRESO);
commit;

